import re
from datetime import date
from io import BytesIO

from fastapi import APIRouter, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from pypdf import PdfReader, PdfWriter
from pypdf.generic import (
    ArrayObject,
    DictionaryObject,
    FloatObject,
    NameObject,
    NumberObject,
    TextStringObject,
)
from reportlab.lib.colors import HexColor, white
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.pdfgen import canvas

from app.api.deps import CurrentUser, DbSession
from app.services.audit import record_audit_event

router = APIRouter(prefix="/document-studio", tags=["document-studio"])

ORANGE = HexColor("#f36f21")
DARK = HexColor("#252525")
MUTED = HexColor("#6b7280")
LIGHT = HexColor("#f5f5f5")
BORDER = HexColor("#d7d7d7")


class LetterheadDocument(BaseModel):
    recipient_name: str = Field(default="The Managing Director", max_length=160)
    recipient_company: str = Field(default="Demo Client (Pty) Ltd", max_length=200)
    recipient_address: str = Field(default="Maseru 100\nLesotho", max_length=500)
    reference: str = Field(default="GRISK/DEMO/001", max_length=80)
    document_date: str = Field(
        default_factory=lambda: date.today().strftime("%d %B %Y"),
        max_length=80,
    )
    subject: str = Field(default="DEMO DOCUMENT STUDIO LETTER", max_length=220)
    body: str = Field(
        default=(
            "Dear Sir/Madam,\n\n"
            "This demonstration letter was generated by the gRisk Document Studio. "
            "It uses a Guardrisk-style letterhead and includes a real PDF digital signature field.\n\n"
            "The studio is intended to let authorised staff prepare formal letters, notices, "
            "policy correspondence, claims communications and other operational documents "
            "from within gRisk, then export them as PDF.\n\n"
            "Please click the signature area in a compatible PDF application to apply a "
            "digital signature."
        ),
        max_length=12000,
    )
    signatory_name: str = Field(default="Authorised Signatory", max_length=160)
    signatory_title: str = Field(default="Guardrisk Insurance Brokers", max_length=160)
    include_signature_field: bool = True


def _wrap_line(
    text: str,
    font_name: str,
    font_size: float,
    max_width: float,
) -> list[str]:
    words = text.split()
    if not words:
        return [""]
    lines: list[str] = []
    current = words[0]
    for word in words[1:]:
        candidate = f"{current} {word}"
        if stringWidth(candidate, font_name, font_size) <= max_width:
            current = candidate
        else:
            lines.append(current)
            current = word
    lines.append(current)
    return lines


def _draw_letterhead(c: canvas.Canvas, page_number: int) -> None:
    width, height = A4
    c.setFillColor(ORANGE)
    c.rect(0, height - 27 * mm, width, 27 * mm, fill=1, stroke=0)

    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(18 * mm, height - 14 * mm, "Guardrisk")
    c.setFont("Helvetica-Bold", 9.5)
    c.drawString(18 * mm, height - 20 * mm, "INSURANCE BROKERS")
    c.setFont("Helvetica", 7.6)
    c.drawRightString(width - 18 * mm, height - 12 * mm, "gRisk Document Studio")
    c.drawRightString(
        width - 18 * mm,
        height - 17 * mm,
        "Insurance | Medical Aid | Risk Management",
    )
    c.drawRightString(width - 18 * mm, height - 22 * mm, "Maseru, Lesotho")

    c.setFillColor(LIGHT)
    c.rect(0, height - 33 * mm, width, 6 * mm, fill=1, stroke=0)
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 6.8)
    c.drawString(
        18 * mm,
        height - 30.7 * mm,
        "LNDC Centre, Ground Floor, Kingsway Road, Maseru 100",
    )
    c.drawRightString(
        width - 18 * mm,
        height - 30.7 * mm,
        "+266 2232 2537 | info@guardrisk.co.ls",
    )

    c.setStrokeColor(ORANGE)
    c.setLineWidth(1)
    c.line(18 * mm, 17 * mm, width - 18 * mm, 17 * mm)
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 6.7)
    c.drawString(
        18 * mm,
        11.5 * mm,
        "Guardrisk Insurance Brokers | IBR No. 69915",
    )
    c.drawRightString(width - 18 * mm, 11.5 * mm, f"Page {page_number}")


def _build_base_pdf(
    payload: LetterheadDocument,
) -> tuple[bytes, int, tuple[float, float, float, float] | None]:
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    left = 20 * mm
    right = width - 20 * mm
    max_width = right - left
    page_number = 1
    y = height - 46 * mm

    def new_page() -> None:
        nonlocal page_number, y
        c.showPage()
        page_number += 1
        _draw_letterhead(c, page_number)
        y = height - 46 * mm

    _draw_letterhead(c, page_number)

    c.setFillColor(DARK)
    c.setFont("Helvetica", 9)
    c.drawRightString(right, y, payload.document_date)
    y -= 6 * mm
    c.setFont("Helvetica-Bold", 8.5)
    c.drawRightString(right, y, f"Ref: {payload.reference}")

    c.setFont("Helvetica", 10)
    recipient_lines = [
        payload.recipient_name,
        payload.recipient_company,
        *payload.recipient_address.splitlines(),
    ]
    y -= 4 * mm
    for line in recipient_lines:
        if line.strip():
            y -= 5.2 * mm
            c.drawString(left, y, line.strip())

    y -= 8 * mm
    c.setFillColor(ORANGE)
    c.setFont("Helvetica-Bold", 10.5)
    subject_lines = _wrap_line(
        payload.subject.upper(),
        "Helvetica-Bold",
        10.5,
        max_width,
    )
    for line in subject_lines:
        c.drawString(left, y, line)
        y -= 5.3 * mm

    c.setFillColor(DARK)
    c.setFont("Helvetica", 10)
    y -= 2 * mm

    for paragraph in payload.body.replace("\r\n", "\n").split("\n"):
        if not paragraph.strip():
            y -= 4.2 * mm
            continue
        for line in _wrap_line(paragraph.strip(), "Helvetica", 10, max_width):
            if y < 50 * mm:
                new_page()
                c.setFillColor(DARK)
                c.setFont("Helvetica", 10)
            c.drawString(left, y, line)
            y -= 5.2 * mm
        y -= 1.5 * mm

    required_signature_space = 48 * mm
    if y < 22 * mm + required_signature_space:
        new_page()

    y -= 5 * mm
    c.setFillColor(DARK)
    c.setFont("Helvetica", 10)
    c.drawString(left, y, "Yours faithfully,")
    y -= 8 * mm

    signature_rect: tuple[float, float, float, float] | None = None
    if payload.include_signature_field:
        sig_width = 82 * mm
        sig_height = 22 * mm
        sig_x = left
        sig_y = y - sig_height
        c.setStrokeColor(BORDER)
        c.setDash(4, 3)
        c.rect(sig_x, sig_y, sig_width, sig_height, fill=0, stroke=1)
        c.setDash()
        c.setFillColor(MUTED)
        c.setFont("Helvetica", 7.5)
        c.drawString(
            sig_x + 3 * mm,
            sig_y + 3 * mm,
            "Digital signature field - click here to sign",
        )
        signature_rect = (sig_x, sig_y, sig_x + sig_width, sig_y + sig_height)
        y = sig_y - 6 * mm
    else:
        y -= 12 * mm
        c.setStrokeColor(DARK)
        c.line(left, y, left + 70 * mm, y)
        y -= 6 * mm

    c.setFillColor(DARK)
    c.setFont("Helvetica-Bold", 9.5)
    c.drawString(left, y, payload.signatory_name)
    y -= 4.5 * mm
    c.setFont("Helvetica", 8.8)
    c.drawString(left, y, payload.signatory_title)

    c.save()
    buffer.seek(0)
    return buffer.getvalue(), page_number - 1, signature_rect


def _add_signature_field(
    pdf_bytes: bytes,
    page_index: int,
    rect: tuple[float, float, float, float],
) -> bytes:
    reader = PdfReader(BytesIO(pdf_bytes))
    writer = PdfWriter()
    writer.append_pages_from_reader(reader)
    page = writer.pages[page_index]

    signature = DictionaryObject(
        {
            NameObject("/FT"): NameObject("/Sig"),
            NameObject("/Type"): NameObject("/Annot"),
            NameObject("/Subtype"): NameObject("/Widget"),
            NameObject("/T"): TextStringObject("signature"),
            NameObject("/TU"): TextStringObject("Authorised digital signature"),
            NameObject("/F"): NumberObject(4),
            NameObject("/Rect"): ArrayObject(
                [FloatObject(value) for value in rect]
            ),
            NameObject("/P"): page.indirect_reference,
        }
    )
    signature_ref = writer._add_object(signature)
    annotations = page.get("/Annots")
    if annotations is None:
        annotations = ArrayObject()
        page[NameObject("/Annots")] = annotations
    annotations.append(signature_ref)

    acro_form = DictionaryObject(
        {
            NameObject("/Fields"): ArrayObject([signature_ref]),
            NameObject("/SigFlags"): NumberObject(3),
        }
    )
    writer._root_object[NameObject("/AcroForm")] = writer._add_object(acro_form)

    output = BytesIO()
    writer.write(output)
    return output.getvalue()


def render_letterhead_pdf(payload: LetterheadDocument) -> bytes:
    base, signature_page, signature_rect = _build_base_pdf(payload)
    if not payload.include_signature_field or signature_rect is None:
        return base
    return _add_signature_field(base, signature_page, signature_rect)


def _filename(subject: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9]+", "-", subject).strip("-").lower()
    return f"{cleaned[:70] or 'guardrisk-letter'}.pdf"


@router.post("/render")
async def render_document(
    payload: LetterheadDocument,
    request: Request,
    user: CurrentUser,
    session: DbSession,
) -> StreamingResponse:
    pdf_bytes = render_letterhead_pdf(payload)
    await record_audit_event(
        session,
        action="document_studio.generated",
        entity_type="generated_document",
        entity_id=payload.reference,
        actor_user_id=user.id,
        details={
            "subject": payload.subject,
            "reference": payload.reference,
            "signature_field": payload.include_signature_field,
        },
        ip_address=request.client.host if request.client else None,
    )
    await session.commit()
    filename = _filename(payload.subject)
    return StreamingResponse(
        BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
