import re
from datetime import UTC, datetime
from io import BytesIO

from fastapi import APIRouter, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from pypdf import PdfReader, PdfWriter
from pypdf.generic import (
    ArrayObject,
    BooleanObject,
    DictionaryObject,
    FloatObject,
    NameObject,
    NumberObject,
    TextStringObject,
)
from reportlab.lib.colors import HexColor, white
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.pdfgen import canvas

from app.api.deps import CurrentUser, DbSession
from app.services.audit import record_audit_event

router = APIRouter(prefix="/document-studio", tags=["document-studio"])

# Guardrisk visual language - bright orange, white and restrained charcoal.
ORANGE = HexColor("#F35A1F")
ORANGE_DARK = HexColor("#D94A13")
ORANGE_SOFT = HexColor("#FFF3EC")
INK = HexColor("#242424")
MUTED = HexColor("#6B7280")
PALE = HexColor("#F7F7F7")
BORDER = HexColor("#DEDEDE")


class LetterheadDocument(BaseModel):
    document_title: str = Field(default="FORMAL CORRESPONDENCE", max_length=160)
    recipient_name: str = Field(default="The Managing Director", max_length=160)
    recipient_company: str = Field(default="Demo Client (Pty) Ltd", max_length=200)
    recipient_address: str = Field(default="Maseru 100\nLesotho", max_length=500)
    recipient_phone: str = Field(default="", max_length=100)
    recipient_email: str = Field(default="", max_length=160)
    reference: str = Field(default="GRISK/DEMO/001", max_length=80)
    document_date: str = Field(
        default_factory=lambda: datetime.now(UTC).strftime("%d %B %Y"),
        max_length=80,
    )
    subject: str = Field(default="DEMO DOCUMENT STUDIO LETTER", max_length=220)
    body: str = Field(
        default=(
            "Dear Sir/Madam,\n\n"
            "This demonstration letter was generated by the gRisk Document Studio. "
            "The template uses the Guardrisk orange and white identity with a simple "
            "corporate layout that keeps the page bright, formal and easy to read.\n\n"
            "The exported PDF includes a real digital-signature field. In a compatible "
            "PDF application, an authorised signatory can click the signature area and "
            "apply a certificate-based signature without rebuilding the document.\n\n"
            "The same template can be used for quotations, policy correspondence, claims, "
            "medical aid, finance, bonds, risk management and general client communications."
        ),
        max_length=12000,
    )
    signatory_name: str = Field(default="Authorised Signatory", max_length=160)
    signatory_title: str = Field(default="Guardrisk Insurance Brokers", max_length=160)
    signatory_contact: str = Field(
        default="+266 2232 2537 | info@guardrisk.co.ls",
        max_length=220,
    )
    include_signature_field: bool = True
    include_document_stamp: bool = True


def _wrap_line(
    text: str,
    font_name: str,
    font_size: float,
    max_width: float,
) -> list[str]:
    words = text.split()
    if not words:
        return [""]
    lines: list[str] = []
    current = words[0]
    for word in words[1:]:
        candidate = f"{current} {word}"
        if stringWidth(candidate, font_name, font_size) <= max_width:
            current = candidate
        else:
            lines.append(current)
            current = word
    lines.append(current)
    return lines


def _draw_brand_mark(c: canvas.Canvas, x: float, y: float) -> None:
    radius = 8.2 * mm
    c.setFillColor(ORANGE)
    c.circle(x, y, radius, fill=1, stroke=0)
    c.setStrokeColor(ORANGE_DARK)
    c.setLineWidth(0.6)
    c.circle(x, y, radius, fill=0, stroke=1)
    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 17)
    c.drawCentredString(x, y - 5.4, "G")


def _draw_top_accent(c: canvas.Canvas) -> None:
    _, height = A4
    path = c.beginPath()
    path.moveTo(0, height)
    path.lineTo(82 * mm, height)
    path.curveTo(49 * mm, height - 1 * mm, 24 * mm, height - 9 * mm, 0, height - 25 * mm)
    path.close()
    c.setFillColor(ORANGE)
    c.drawPath(path, fill=1, stroke=0)

    c.setStrokeColor(HexColor("#FFB08A"))
    c.setLineWidth(1.2)
    path = c.beginPath()
    path.moveTo(0, height - 28 * mm)
    path.curveTo(22 * mm, height - 11 * mm, 51 * mm, height - 3 * mm, 86 * mm, height)
    c.drawPath(path, fill=0, stroke=1)


def _draw_bottom_accent(c: canvas.Canvas) -> None:
    width, _ = A4
    path = c.beginPath()
    path.moveTo(0, 0)
    path.lineTo(width, 0)
    path.lineTo(width, 12 * mm)
    path.curveTo(width - 36 * mm, 3 * mm, width - 78 * mm, 17 * mm, width - 118 * mm, 8 * mm)
    path.curveTo(width - 154 * mm, 0, width - 180 * mm, 1 * mm, 0, 8 * mm)
    path.close()
    c.setFillColor(ORANGE)
    c.drawPath(path, fill=1, stroke=0)


def _draw_letterhead(c: canvas.Canvas, page_number: int, document_title: str) -> None:
    width, height = A4
    center = width / 2

    _draw_top_accent(c)
    _draw_bottom_accent(c)

    mark_y = height - 18 * mm
    _draw_brand_mark(c, center, mark_y)

    c.setFillColor(ORANGE)
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(center, height - 32 * mm, "GUARDRISK")
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 7.4)
    c.drawCentredString(center, height - 37 * mm, "DOCUMENT STUDIO")
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 6.5)
    c.drawCentredString(
        center,
        height - 42 * mm,
        "Insurance  |  Medical Aid  |  Bonds  |  Risk Management",
    )

    c.setStrokeColor(ORANGE)
    c.setLineWidth(0.9)
    c.line(18 * mm, height - 47 * mm, width - 18 * mm, height - 47 * mm)

    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 10.2)
    c.drawCentredString(center, height - 54.5 * mm, document_title.upper())

    c.setStrokeColor(HexColor("#E9E9E9"))
    c.setLineWidth(0.7)
    c.line(18 * mm, 21.5 * mm, width - 18 * mm, 21.5 * mm)
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 6.4)
    c.drawCentredString(
        center,
        15.7 * mm,
        "Guardrisk Insurance Brokers | LNDC Centre, Kingsway Road, Maseru 100 | "
        "+266 2232 2537 | info@guardrisk.co.ls",
    )
    c.drawRightString(width - 18 * mm, 11.5 * mm, f"Page {page_number}")


def _draw_recipient_panel(
    c: canvas.Canvas,
    payload: LetterheadDocument,
    y_top: float,
) -> float:
    width, _ = A4
    left = 18 * mm
    right = width - 18 * mm
    panel_height = 38 * mm
    panel_bottom = y_top - panel_height

    c.setFillColor(PALE)
    c.setStrokeColor(BORDER)
    c.setLineWidth(0.7)
    c.roundRect(left, panel_bottom, right - left, panel_height, 3 * mm, fill=1, stroke=1)
    c.setFillColor(ORANGE)
    c.roundRect(left, panel_bottom, 3 * mm, panel_height, 3 * mm, fill=1, stroke=0)
    c.rect(left + 1.5 * mm, panel_bottom, 1.5 * mm, panel_height, fill=1, stroke=0)

    x = left + 8 * mm
    y = y_top - 7.4 * mm
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 7.7)
    c.drawString(x, y, "Date:")
    c.setFont("Helvetica", 7.7)
    c.drawString(x + 13 * mm, y, payload.document_date)

    c.setFont("Helvetica-Bold", 7.7)
    c.drawRightString(right - 32 * mm, y, "Reference:")
    c.setFont("Helvetica", 7.7)
    c.drawRightString(right - 5 * mm, y, payload.reference)

    y -= 5.4 * mm
    c.setFont("Helvetica-Bold", 7.7)
    c.drawString(x, y, "To:")
    c.setFont("Helvetica-Bold", 8.1)
    c.drawString(x + 13 * mm, y, payload.recipient_name)

    y -= 4.8 * mm
    c.setFont("Helvetica", 7.6)
    c.drawString(x + 13 * mm, y, payload.recipient_company)
    for address_line in payload.recipient_address.splitlines()[:2]:
        if address_line.strip():
            y -= 4.3 * mm
            c.drawString(x + 13 * mm, y, address_line.strip())

    details: list[str] = []
    if payload.recipient_phone.strip():
        details.append(f"Tel: {payload.recipient_phone.strip()}")
    if payload.recipient_email.strip():
        details.append(f"Email: {payload.recipient_email.strip()}")
    if details:
        c.setFillColor(MUTED)
        c.setFont("Helvetica", 7.0)
        c.drawRightString(right - 5 * mm, panel_bottom + 5 * mm, "   |   ".join(details))

    return panel_bottom


def _draw_document_stamp(c: canvas.Canvas, x: float, y: float) -> None:
    c.setStrokeColor(ORANGE)
    c.setLineWidth(1.2)
    c.circle(x, y, 16.5 * mm, fill=0, stroke=1)
    c.setStrokeColor(HexColor("#FFB08A"))
    c.setLineWidth(0.8)
    c.circle(x, y, 13.9 * mm, fill=0, stroke=1)
    c.setFillColor(ORANGE)
    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(x, y + 5.8 * mm, "G")
    c.setFont("Helvetica-Bold", 6.0)
    c.drawCentredString(x, y + 0.4 * mm, "DOCUMENT STUDIO")
    c.setFillColor(MUTED)
    c.setFont("Helvetica-Bold", 5.4)
    c.drawCentredString(x, y - 4.2 * mm, "SIGNING READY")
    c.setFont("Helvetica", 4.9)
    c.drawCentredString(x, y - 8.0 * mm, "gRisk")


def _draw_signature_panel(
    c: canvas.Canvas,
    payload: LetterheadDocument,
    y_top: float,
) -> tuple[float, tuple[float, float, float, float] | None]:
    width, _ = A4
    left = 18 * mm
    right = width - 18 * mm
    panel_height = 46 * mm
    panel_bottom = y_top - panel_height

    c.setFillColor(white)
    c.setStrokeColor(ORANGE)
    c.setLineWidth(0.9)
    c.roundRect(left, panel_bottom, right - left, panel_height, 3 * mm, fill=1, stroke=1)

    x = left + 7 * mm
    y = y_top - 8.5 * mm
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 9.2)
    c.drawString(x, y, payload.signatory_name)
    y -= 5.1 * mm
    c.setFont("Helvetica-Bold", 7.5)
    c.drawString(x, y, payload.signatory_title)
    y -= 4.6 * mm
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 7.0)
    c.drawString(x, y, payload.signatory_contact)

    field_left = x
    field_bottom = panel_bottom + 7.3 * mm
    field_width = 78 * mm
    field_height = 13 * mm
    signature_rect: tuple[float, float, float, float] | None = None

    c.setFillColor(ORANGE)
    c.setFont("Helvetica-Bold", 5.8)
    c.drawString(field_left, field_bottom + field_height + 2.1 * mm, "AUTHORISED SIGNATURE")
    if payload.include_signature_field:
        c.setFillColor(white)
        c.setStrokeColor(ORANGE)
        c.setLineWidth(0.8)
        c.roundRect(field_left, field_bottom, field_width, field_height, 2 * mm, fill=1, stroke=1)
        c.setFillColor(MUTED)
        c.setFont("Helvetica", 6.1)
        c.drawString(
            field_left + 3 * mm,
            field_bottom + 4.6 * mm,
            "Click here to apply a certificate-based digital signature",
        )
        signature_rect = (
            field_left,
            field_bottom,
            field_left + field_width,
            field_bottom + field_height,
        )
    else:
        c.setStrokeColor(INK)
        c.line(field_left, field_bottom, field_left + field_width, field_bottom)

    date_x = field_left + field_width + 8 * mm
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 5.8)
    c.drawString(date_x, field_bottom + field_height + 2.1 * mm, "DATE SIGNED")
    c.setStrokeColor(HexColor("#8C8C8C"))
    c.line(date_x, field_bottom, date_x + 35 * mm, field_bottom)

    if payload.include_document_stamp:
        _draw_document_stamp(c, right - 23 * mm, panel_bottom + panel_height / 2)

    return panel_bottom, signature_rect


def _build_base_pdf(
    payload: LetterheadDocument,
) -> tuple[bytes, int, tuple[float, float, float, float] | None]:
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    left = 18 * mm
    right = width - 18 * mm
    max_width = right - left
    page_number = 1
    y = height - 62 * mm

    def new_page() -> None:
        nonlocal page_number, y
        c.showPage()
        page_number += 1
        _draw_letterhead(c, page_number, payload.document_title)
        y = height - 62 * mm

    _draw_letterhead(c, page_number, payload.document_title)
    y = _draw_recipient_panel(c, payload, y)
    y -= 8.5 * mm

    c.setFillColor(ORANGE)
    c.setFont("Helvetica-Bold", 9.6)
    subject = f"RE: {payload.subject.upper()}"
    for line in _wrap_line(subject, "Helvetica-Bold", 9.6, max_width):
        c.drawString(left, y, line)
        y -= 5.1 * mm
    c.setStrokeColor(ORANGE)
    c.setLineWidth(0.65)
    c.line(left, y + 1.4 * mm, right, y + 1.4 * mm)

    y -= 1.6 * mm
    c.setFillColor(INK)
    c.setFont("Helvetica", 9.4)
    for paragraph in payload.body.replace("\r\n", "\n").split("\n"):
        if not paragraph.strip():
            y -= 4 * mm
            continue
        for line in _wrap_line(paragraph.strip(), "Helvetica", 9.4, max_width):
            if y < 75 * mm:
                new_page()
                c.setFillColor(INK)
                c.setFont("Helvetica", 9.4)
            c.drawString(left, y, line)
            y -= 4.8 * mm
        y -= 1.2 * mm

    if y < 80 * mm:
        new_page()

    y -= 4 * mm
    c.setFillColor(INK)
    c.setFont("Helvetica", 9.2)
    c.drawString(left, y, "Yours faithfully,")
    y -= 7 * mm

    _, signature_rect = _draw_signature_panel(c, payload, y)
    signature_page_index = page_number - 1

    c.save()
    buffer.seek(0)
    return buffer.getvalue(), signature_page_index, signature_rect


def _add_signature_field(
    pdf_bytes: bytes,
    page_index: int,
    rect: tuple[float, float, float, float],
) -> bytes:
    reader = PdfReader(BytesIO(pdf_bytes))
    writer = PdfWriter()
    writer.append_pages_from_reader(reader)
    page = writer.pages[page_index]

    signature = DictionaryObject(
        {
            NameObject("/FT"): NameObject("/Sig"),
            NameObject("/Type"): NameObject("/Annot"),
            NameObject("/Subtype"): NameObject("/Widget"),
            NameObject("/T"): TextStringObject("signature"),
            NameObject("/TU"): TextStringObject("Authorised digital signature"),
            NameObject("/F"): NumberObject(4),
            NameObject("/Rect"): ArrayObject([FloatObject(value) for value in rect]),
            NameObject("/P"): page.indirect_reference,
        }
    )
    signature_ref = writer._add_object(signature)
    annotations = page.get("/Annots")
    if annotations is None:
        annotations = ArrayObject()
        page[NameObject("/Annots")] = annotations
    annotations.append(signature_ref)

    acro_form = DictionaryObject(
        {
            NameObject("/Fields"): ArrayObject([signature_ref]),
            NameObject("/SigFlags"): NumberObject(3),
            NameObject("/NeedAppearances"): BooleanObject(False),
        }
    )
    writer._root_object[NameObject("/AcroForm")] = writer._add_object(acro_form)
    writer.add_metadata(
        {
            "/Title": "Guardrisk Document Studio Letter",
            "/Author": "Guardrisk Insurance Brokers",
            "/Creator": "gRisk Document Studio",
        }
    )

    output = BytesIO()
    writer.write(output)
    return output.getvalue()


def render_letterhead_pdf(payload: LetterheadDocument) -> bytes:
    base, signature_page, signature_rect = _build_base_pdf(payload)
    if not payload.include_signature_field or signature_rect is None:
        return base
    return _add_signature_field(base, signature_page, signature_rect)


def _filename(subject: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9]+", "-", subject).strip("-").lower()
    return f"{cleaned[:70] or 'guardrisk-letter'}.pdf"


@router.post("/render")
async def render_document(
    payload: LetterheadDocument,
    request: Request,
    user: CurrentUser,
    session: DbSession,
) -> StreamingResponse:
    pdf_bytes = render_letterhead_pdf(payload)
    await record_audit_event(
        session,
        action="document_studio.generated",
        entity_type="generated_document",
        entity_id=payload.reference,
        actor_user_id=user.id,
        details={
            "document_title": payload.document_title,
            "subject": payload.subject,
            "reference": payload.reference,
            "signature_field": payload.include_signature_field,
            "document_stamp": payload.include_document_stamp,
            "template": "guardrisk-orange-letterhead",
        },
        ip_address=request.client.host if request.client else None,
    )
    await session.commit()
    filename = _filename(payload.subject)
    return StreamingResponse(
        BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )