"use client";

import { useState } from "react";
import AppShell from "@/components/AppShell";
import { apiDownloadPost } from "@/lib/api";
import { currentUser } from "@/lib/auth";

interface StudioDocument {
  document_title: string;
  recipient_name: string;
  recipient_company: string;
  recipient_address: string;
  recipient_phone: string;
  recipient_email: string;
  reference: string;
  document_date: string;
  subject: string;
  body: string;
  signatory_name: string;
  signatory_title: string;
  signatory_contact: string;
  include_signature_field: boolean;
  include_document_stamp: boolean;
}

const demoDocument: StudioDocument = {
  document_title: "FORMAL CORRESPONDENCE",
  recipient_name: "The Managing Director",
  recipient_company: "Demo Client (Pty) Ltd",
  recipient_address: "Maseru 100\nLesotho",
  recipient_phone: "+266 2231 0000",
  recipient_email: "director@democlient.co.ls",
  reference: "GRISK/DEMO/001",
  document_date: "08 September 2026",
  subject: "Demonstration of the gRisk Document Studio",
  body:
    "Dear Sir/Madam,\n\n" +
    "This demonstration letter was generated by the gRisk Document Studio using the refreshed Guardrisk executive letterhead. The design is intentionally formal, spacious and suitable for client-facing correspondence.\n\n" +
    "The exported PDF includes a real digital-signature field. In a compatible PDF application, an authorised signatory can click the signature area and apply a certificate-based signature without rebuilding the document.\n\n" +
    "The same studio can be used for quotations, policy correspondence, claims, medical aid, finance, bonds, risk management and general operational letters.",
  signatory_name: "Authorised Signatory",
  signatory_title: "Guardrisk Insurance Brokers",
  signatory_contact: "+266 2232 2537 | info@guardrisk.co.ls",
  include_signature_field: true,
  include_document_stamp: true,
};

function Field({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) {
  return (
    <div className={wide ? "field full" : "field"}>
      <label>{label}</label>
      {children}
    </div>
  );
}

export default function DocumentStudioPage() {
  const user = currentUser();
  const canGenerate = Boolean(
    user?.isSuperuser ||
      user?.roles.some((role) => ["admin", "broker", "claims", "medical", "finance", "risk"].includes(role)),
  );
  const [document, setDocument] = useState<StudioDocument>({ ...demoDocument });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");

  function update<K extends keyof StudioDocument>(key: K, value: StudioDocument[K]) {
    setDocument((current) => ({ ...current, [key]: value }));
  }

  async function exportPdf() {
    setBusy(true);
    setError("");
    setNotice("");
    try {
      const result = await apiDownloadPost("/api/v1/document-studio/render", document);
      const url = URL.createObjectURL(result.blob);
      const anchor = window.document.createElement("a");
      anchor.href = url;
      anchor.download = result.filename || "guardrisk-document.pdf";
      anchor.click();
      URL.revokeObjectURL(url);
      setNotice("PDF generated with a real digital-signature field and the executive Guardrisk letterhead.");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unable to generate the PDF.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <AppShell>
      <div className="page-head">
        <div>
          <h1>Document Studio</h1>
          <p>Create polished Guardrisk correspondence with a live A4 preview and signing-ready PDF output.</p>
        </div>
        <div className="page-actions">
          <button className="button secondary" onClick={() => setDocument({ ...demoDocument })} disabled={busy}>
            Reset demo
          </button>
          <button className="button" onClick={() => void exportPdf()} disabled={busy || !canGenerate}>
            {busy ? "Generating PDF…" : "Export signing-ready PDF"}
          </button>
        </div>
      </div>

      {error && <div className="notice error" style={{ marginBottom: 14 }}>{error}</div>}
      {notice && <div className="notice" style={{ marginBottom: 14 }}>{notice}</div>}
      {!canGenerate && (
        <div className="notice" style={{ marginBottom: 14 }}>
          Your current role can preview the studio but cannot generate operational documents.
        </div>
      )}

      <div className="studio-v2-grid">
        <div className="studio-v2-controls">
          <section className="card pad studio-v2-template-card">
            <div className="studio-v2-template-top">
              <div className="studio-v2-template-mark">gR</div>
              <div>
                <div className="studio-v2-eyebrow">ACTIVE TEMPLATE</div>
                <h2>Executive Letterhead</h2>
                <p>Centered corporate identity, light recipient panel, strong subject hierarchy and a formal signature block.</p>
              </div>
            </div>
            <div className="studio-v2-feature-row">
              <span>Premium A4</span>
              <span>Signature field</span>
              <span>Document stamp</span>
              <span>Audit logged</span>
            </div>
          </section>

          <section className="card pad">
            <div className="card-header studio-v2-card-head">
              <div>
                <h2>Document identity</h2>
                <p>Controls the title and reference shown on the letterhead.</p>
              </div>
            </div>
            <div className="form-grid">
              <Field label="Document title" wide>
                <input className="input" value={document.document_title} onChange={(e) => update("document_title", e.target.value)} />
              </Field>
              <Field label="Date">
                <input className="input" value={document.document_date} onChange={(e) => update("document_date", e.target.value)} />
              </Field>
              <Field label="Reference">
                <input className="input" value={document.reference} onChange={(e) => update("reference", e.target.value)} />
              </Field>
            </div>
          </section>

          <section className="card pad">
            <div className="card-header studio-v2-card-head">
              <div>
                <h2>Recipient</h2>
                <p>These details are presented in a formal recipient card.</p>
              </div>
            </div>
            <div className="form-grid">
              <Field label="Recipient">
                <input className="input" value={document.recipient_name} onChange={(e) => update("recipient_name", e.target.value)} />
              </Field>
              <Field label="Organisation">
                <input className="input" value={document.recipient_company} onChange={(e) => update("recipient_company", e.target.value)} />
              </Field>
              <Field label="Address" wide>
                <textarea className="textarea" style={{ minHeight: 76 }} value={document.recipient_address} onChange={(e) => update("recipient_address", e.target.value)} />
              </Field>
              <Field label="Telephone">
                <input className="input" value={document.recipient_phone} onChange={(e) => update("recipient_phone", e.target.value)} />
              </Field>
              <Field label="Email">
                <input className="input" value={document.recipient_email} onChange={(e) => update("recipient_email", e.target.value)} />
              </Field>
            </div>
          </section>

          <section className="card pad">
            <div className="card-header studio-v2-card-head">
              <div>
                <h2>Letter content</h2>
                <p>Keep the writing clear; the PDF automatically wraps and continues onto additional pages.</p>
              </div>
            </div>
            <div className="form-grid">
              <Field label="Subject" wide>
                <input className="input" value={document.subject} onChange={(e) => update("subject", e.target.value)} />
              </Field>
              <Field label="Letter body" wide>
                <textarea className="textarea" style={{ minHeight: 285 }} value={document.body} onChange={(e) => update("body", e.target.value)} />
              </Field>
            </div>
          </section>

          <section className="card pad">
            <div className="card-header studio-v2-card-head">
              <div>
                <h2>Signatory</h2>
                <p>The signature area is designed to look complete even before a certificate is applied.</p>
              </div>
            </div>
            <div className="form-grid">
              <Field label="Name">
                <input className="input" value={document.signatory_name} onChange={(e) => update("signatory_name", e.target.value)} />
              </Field>
              <Field label="Title / organisation">
                <input className="input" value={document.signatory_title} onChange={(e) => update("signatory_title", e.target.value)} />
              </Field>
              <Field label="Contact" wide>
                <input className="input" value={document.signatory_contact} onChange={(e) => update("signatory_contact", e.target.value)} />
              </Field>
              <Field label="Signing options" wide>
                <div className="studio-v2-options">
                  <label>
                    <input type="checkbox" checked={document.include_signature_field} onChange={(e) => update("include_signature_field", e.target.checked)} />
                    <span><strong>Digital signature field</strong><small>Creates a real PDF /Sig field for certificate signing.</small></span>
                  </label>
                  <label>
                    <input type="checkbox" checked={document.include_document_stamp} onChange={(e) => update("include_document_stamp", e.target.checked)} />
                    <span><strong>Document Studio stamp</strong><small>Adds a neutral “signing ready” stamp - not a fake signed seal.</small></span>
                  </label>
                </div>
              </Field>
            </div>
          </section>
        </div>

        <section className="card studio-v2-preview-card">
          <div className="studio-v2-preview-head">
            <div>
              <strong>Live A4 preview</strong>
              <span>Executive letterhead · PDF output mirrors this layout</span>
            </div>
            <span className="badge active">Signing ready</span>
          </div>

          <div className="studio-v2-paper-wrap">
            <article className="studio-v2-paper">
              <header className="studio-v2-letterhead">
                <div className="studio-v2-logo-mark"><span>gR</span></div>
                <div className="studio-v2-brand">GUARDRISK</div>
                <div className="studio-v2-brand-sub">INSURANCE BROKERS</div>
                <div className="studio-v2-services">Insurance&nbsp;&nbsp; | &nbsp;&nbsp;Medical Aid&nbsp;&nbsp; | &nbsp;&nbsp;Bonds&nbsp;&nbsp; | &nbsp;&nbsp;Risk Management</div>
                <div className="studio-v2-gold-rule" />
                <div className="studio-v2-document-title">{document.document_title.toUpperCase()}</div>
              </header>

              <div className="studio-v2-recipient-card">
                <div className="studio-v2-recipient-accent" />
                <div className="studio-v2-recipient-content">
                  <div className="studio-v2-meta-row">
                    <div><strong>Date:</strong><span>{document.document_date}</span></div>
                    <div><strong>Reference:</strong><span>{document.reference}</span></div>
                  </div>
                  <div className="studio-v2-to-row"><strong>To:</strong><span>{document.recipient_name}</span></div>
                  <div className="studio-v2-recipient-company">{document.recipient_company}</div>
                  <div className="studio-v2-address">{document.recipient_address}</div>
                  {(document.recipient_phone || document.recipient_email) && (
                    <div className="studio-v2-recipient-contact">
                      {document.recipient_phone && <span>Tel: {document.recipient_phone}</span>}
                      {document.recipient_phone && document.recipient_email && <i>•</i>}
                      {document.recipient_email && <span>Email: {document.recipient_email}</span>}
                    </div>
                  )}
                </div>
              </div>

              <div className="studio-v2-letter-body">
                <div className="studio-v2-subject">RE: {document.subject.toUpperCase()}</div>
                <div className="studio-v2-body-copy">{document.body}</div>
                <div className="studio-v2-closing">Yours faithfully,</div>

                <div className="studio-v2-signature-panel">
                  <div className="studio-v2-signatory-copy">
                    <strong>{document.signatory_name}</strong>
                    <b>{document.signatory_title}</b>
                    <span>{document.signatory_contact}</span>
                    <div className="studio-v2-sign-row">
                      <div>
                        <label>AUTHORISED SIGNATURE</label>
                        {document.include_signature_field ? (
                          <div className="studio-v2-signature-field">Click here to apply a certificate-based digital signature</div>
                        ) : (
                          <div className="studio-v2-signature-line" />
                        )}
                      </div>
                      <div className="studio-v2-date-field">
                        <label>DATE SIGNED</label>
                        <div />
                      </div>
                    </div>
                  </div>

                  {document.include_document_stamp && (
                    <div className="studio-v2-stamp">
                      <span>GUARDRISK</span>
                      <i />
                      <b>DOCUMENT STUDIO</b>
                      <em>SIGNING READY</em>
                      <small>gRisk</small>
                    </div>
                  )}
                </div>
              </div>

              <footer className="studio-v2-letter-footer">
                <div />
                <span>Guardrisk Insurance Brokers | LNDC Centre, Kingsway Road, Maseru 100 | +266 2232 2537 | info@guardrisk.co.ls</span>
                <small>Page 1</small>
              </footer>
            </article>
          </div>
        </section>
      </div>

      <style jsx global>{`
        .studio-v2-grid {
          display: grid;
          grid-template-columns: minmax(330px, 0.8fr) minmax(570px, 1.2fr);
          gap: 18px;
          align-items: start;
        }
        .studio-v2-controls { display: grid; gap: 18px; }
        .studio-v2-template-card {
          background: linear-gradient(140deg, #ffffff 0%, #f8fbff 66%, #fff8f1 100%);
          border: 1px solid #dce5ef;
        }
        .studio-v2-template-top { display: flex; gap: 15px; align-items: flex-start; }
        .studio-v2-template-mark {
          width: 52px; height: 52px; border-radius: 50%; border: 2px solid #123b69;
          box-shadow: inset 0 0 0 3px white, inset 0 0 0 4px #d7a72d;
          display: grid; place-items: center; color: #123b69; font-weight: 800; flex: 0 0 auto;
        }
        .studio-v2-eyebrow { font-size: 10px; letter-spacing: .13em; color: #d17a20; font-weight: 800; margin-bottom: 4px; }
        .studio-v2-template-card h2 { margin: 0; color: #123b69; }
        .studio-v2-template-card p { margin: 5px 0 0; color: #667085; line-height: 1.5; }
        .studio-v2-feature-row { display: flex; flex-wrap: wrap; gap: 7px; margin-top: 16px; }
        .studio-v2-feature-row span { padding: 6px 9px; border-radius: 999px; background: white; border: 1px solid #dce5ef; color: #475467; font-size: 11px; }
        .studio-v2-card-head { padding: 0 0 13px !important; margin-bottom: 16px !important; }
        .studio-v2-card-head p { margin: 4px 0 0; color: #667085; font-size: 12px; }
        .studio-v2-options { display: grid; gap: 10px; }
        .studio-v2-options > label { display: flex; gap: 10px; align-items: flex-start; cursor: pointer; padding: 10px 11px; border: 1px solid #e4e8ee; border-radius: 10px; background: #fbfcfe; }
        .studio-v2-options input { margin-top: 3px; }
        .studio-v2-options span { display: grid; gap: 2px; }
        .studio-v2-options strong { font-size: 12px; color: #344054; }
        .studio-v2-options small { color: #667085; line-height: 1.4; }
        .studio-v2-preview-card { padding: 18px; background: #e9edf2; position: sticky; top: 76px; }
        .studio-v2-preview-head { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 13px; }
        .studio-v2-preview-head > div { display: grid; gap: 2px; }
        .studio-v2-preview-head span:not(.badge) { color: #667085; font-size: 12px; }
        .studio-v2-paper-wrap { max-width: 780px; margin: 0 auto; }
        .studio-v2-paper {
          aspect-ratio: 210 / 297; min-height: 980px; background: #fff; color: #243247;
          position: relative; box-shadow: 0 16px 42px rgba(16, 24, 40, .16); overflow: hidden;
          font-family: Arial, sans-serif;
        }
        .studio-v2-letterhead { padding: 26px 54px 0; text-align: center; }
        .studio-v2-logo-mark {
          width: 46px; height: 46px; border: 2px solid #123b69; border-radius: 50%; margin: 0 auto 10px;
          box-shadow: inset 0 0 0 3px white, inset 0 0 0 4px #d7a72d; display: grid; place-items: center; position: relative;
        }
        .studio-v2-logo-mark::after { content: ""; width: 6px; height: 6px; background: #f36f21; border-radius: 50%; position: absolute; bottom: -8px; }
        .studio-v2-logo-mark span { color: #123b69; font-size: 14px; font-weight: 800; }
        .studio-v2-brand { color: #123b69; font-weight: 800; font-size: 25px; letter-spacing: .035em; margin-top: 13px; }
        .studio-v2-brand-sub { color: #123b69; font-weight: 800; font-size: 10px; letter-spacing: .11em; margin-top: 2px; }
        .studio-v2-services { color: #65758b; font-size: 8.5px; margin-top: 7px; }
        .studio-v2-gold-rule { height: 2px; background: #d7a72d; margin: 14px 0 11px; }
        .studio-v2-document-title { color: #123b69; font-weight: 800; font-size: 14px; letter-spacing: .025em; }
        .studio-v2-recipient-card {
          margin: 18px 44px 0; min-height: 126px; background: #f3f7fc; border: 1px solid #c9d5e3; display: flex;
        }
        .studio-v2-recipient-accent { width: 8px; background: #d7a72d; flex: 0 0 auto; }
        .studio-v2-recipient-content { padding: 17px 20px 14px; width: 100%; font-size: 10.5px; }
        .studio-v2-meta-row { display: flex; justify-content: space-between; gap: 20px; margin-bottom: 9px; }
        .studio-v2-meta-row > div { display: flex; gap: 8px; }
        .studio-v2-meta-row strong, .studio-v2-to-row strong { color: #243247; }
        .studio-v2-meta-row span { color: #344054; }
        .studio-v2-to-row { display: flex; gap: 8px; margin-bottom: 3px; }
        .studio-v2-to-row span { font-weight: 700; color: #123b69; }
        .studio-v2-recipient-company { margin-left: 22px; color: #344054; }
        .studio-v2-address { margin-left: 22px; white-space: pre-line; color: #475467; line-height: 1.4; }
        .studio-v2-recipient-contact { display: flex; justify-content: flex-end; align-items: center; gap: 7px; margin-top: 6px; color: #65758b; font-size: 9px; }
        .studio-v2-recipient-contact i { font-style: normal; color: #d7a72d; }
        .studio-v2-letter-body { padding: 26px 44px 128px; font-size: 11.2px; line-height: 1.55; }
        .studio-v2-subject { color: #123b69; font-weight: 800; font-size: 11.2px; margin-bottom: 14px; }
        .studio-v2-body-copy { white-space: pre-wrap; min-height: 280px; }
        .studio-v2-closing { margin: 19px 0 12px; }
        .studio-v2-signature-panel {
          min-height: 158px; background: #fff9ee; border: 1px solid #d7a72d; display: grid;
          grid-template-columns: 1fr 150px; gap: 18px; padding: 20px 20px 17px; align-items: center;
        }
        .studio-v2-signatory-copy { display: grid; align-content: start; }
        .studio-v2-signatory-copy > strong { color: #0d2c50; font-size: 12px; margin-bottom: 4px; }
        .studio-v2-signatory-copy > b { color: #344054; font-size: 9.5px; margin-bottom: 4px; }
        .studio-v2-signatory-copy > span { color: #65758b; font-size: 9px; }
        .studio-v2-sign-row { display: grid; grid-template-columns: minmax(0, 1fr) 116px; gap: 16px; margin-top: 18px; }
        .studio-v2-sign-row label { display: block; color: #123b69; font-size: 7px; letter-spacing: .05em; font-weight: 800; margin-bottom: 5px; }
        .studio-v2-signature-field { height: 35px; border: 1px solid #123b69; background: white; color: #65758b; font-size: 7.5px; padding: 10px 8px; line-height: 1.3; }
        .studio-v2-signature-line { height: 35px; border-bottom: 1px solid #123b69; }
        .studio-v2-date-field > div { height: 35px; border-bottom: 1px solid #123b69; }
        .studio-v2-stamp {
          width: 115px; height: 115px; border: 2px solid #123b69; border-radius: 50%; box-shadow: inset 0 0 0 4px #fff9ee, inset 0 0 0 5px #d7a72d;
          margin: 0 auto; display: flex; flex-direction: column; align-items: center; justify-content: center; color: #123b69; text-align: center;
        }
        .studio-v2-stamp > span { font-size: 10px; font-weight: 800; }
        .studio-v2-stamp > i { width: 58px; height: 1px; background: #d7a72d; margin: 6px 0 5px; }
        .studio-v2-stamp > b { font-size: 7px; }
        .studio-v2-stamp > em { color: #f36f21; font-style: normal; font-size: 7px; font-weight: 800; margin-top: 4px; }
        .studio-v2-stamp > small { color: #65758b; margin-top: 4px; }
        .studio-v2-letter-footer { position: absolute; left: 44px; right: 44px; bottom: 24px; color: #65758b; font-size: 7.5px; text-align: center; }
        .studio-v2-letter-footer > div { height: 1px; background: #d7a72d; margin-bottom: 8px; }
        .studio-v2-letter-footer small { position: absolute; right: 0; top: 12px; }
        @media (max-width: 1180px) {
          .studio-v2-grid { grid-template-columns: 1fr; }
          .studio-v2-preview-card { position: static; }
        }
        @media (max-width: 720px) {
          .studio-v2-paper { min-height: 760px; }
          .studio-v2-letterhead { padding-left: 30px; padding-right: 30px; }
          .studio-v2-recipient-card { margin-left: 24px; margin-right: 24px; }
          .studio-v2-letter-body { padding-left: 24px; padding-right: 24px; }
          .studio-v2-signature-panel { grid-template-columns: 1fr; }
          .studio-v2-stamp { display: none; }
          .studio-v2-letter-footer { left: 24px; right: 24px; }
        }
      `}</style>
    </AppShell>
  );
}
