"use client";

import { useState } from "react";
import AppShell from "@/components/AppShell";
import { apiDownloadPost } from "@/lib/api";
import { currentUser } from "@/lib/auth";

interface StudioDocument {
  recipient_name: string;
  recipient_company: string;
  recipient_address: string;
  reference: string;
  document_date: string;
  subject: string;
  body: string;
  signatory_name: string;
  signatory_title: string;
  include_signature_field: boolean;
}

const demoDocument: StudioDocument = {
  recipient_name: "The Managing Director",
  recipient_company: "Demo Client (Pty) Ltd",
  recipient_address: "Maseru 100\nLesotho",
  reference: "GRISK/DEMO/001",
  document_date: "08 September 2026",
  subject: "DEMO DOCUMENT STUDIO LETTER",
  body:
    "Dear Sir/Madam,\n\n" +
    "This demonstration letter was generated by the gRisk Document Studio. It uses a Guardrisk-style letterhead and includes a real PDF digital signature field.\n\n" +
    "The studio is intended to let authorised staff prepare formal letters, notices, policy correspondence, claims communications and other operational documents from within gRisk, then export them as PDF.\n\n" +
    "Please click the signature area in a compatible PDF application to apply a digital signature.",
  signatory_name: "Authorised Signatory",
  signatory_title: "Guardrisk Insurance Brokers",
  include_signature_field: true,
};

function Field({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) {
  return (
    <div className={wide ? "field full" : "field"}>
      <label>{label}</label>
      {children}
    </div>
  );
}

export default function DocumentStudioPage() {
  const user = currentUser();
  const canGenerate = Boolean(
    user?.isSuperuser ||
      user?.roles.some((role) => ["admin", "broker", "claims", "medical", "finance", "risk"].includes(role)),
  );
  const [document, setDocument] = useState<StudioDocument>({ ...demoDocument });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");

  function update<K extends keyof StudioDocument>(key: K, value: StudioDocument[K]) {
    setDocument((current) => ({ ...current, [key]: value }));
  }

  async function exportPdf() {
    setBusy(true);
    setError("");
    setNotice("");
    try {
      const result = await apiDownloadPost("/api/v1/document-studio/render", document);
      const url = URL.createObjectURL(result.blob);
      const anchor = window.document.createElement("a");
      anchor.href = url;
      anchor.download = result.filename || "guardrisk-document.pdf";
      anchor.click();
      URL.revokeObjectURL(url);
      setNotice("PDF generated. The signature area is an actual PDF digital-signature field.");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unable to generate the PDF.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <AppShell>
      <div className="page-head">
        <div>
          <h1>Document Studio</h1>
          <p>Create Guardrisk correspondence on a controlled letterhead and export a signing-ready PDF.</p>
        </div>
        <div className="page-actions">
          <button className="button secondary" onClick={() => setDocument({ ...demoDocument })} disabled={busy}>
            Reset demo
          </button>
          <button className="button" onClick={() => void exportPdf()} disabled={busy || !canGenerate}>
            {busy ? "Generating PDF…" : "Export PDF"}
          </button>
        </div>
      </div>

      {error && <div className="notice error" style={{ marginBottom: 14 }}>{error}</div>}
      {notice && <div className="notice" style={{ marginBottom: 14 }}>{notice}</div>}
      {!canGenerate && (
        <div className="notice" style={{ marginBottom: 14 }}>
          Your current role can preview the studio but cannot generate operational documents.
        </div>
      )}

      <div style={{ display: "grid", gridTemplateColumns: "minmax(320px, 0.78fr) minmax(520px, 1.22fr)", gap: 18, alignItems: "start" }} className="studio-grid">
        <div style={{ display: "grid", gap: 18 }}>
          <section className="card pad">
            <div className="card-header" style={{ padding: 0, paddingBottom: 14, marginBottom: 16 }}>
              <div>
                <h2>Template</h2>
                <p>Guardrisk modern letterhead</p>
              </div>
              <span className="badge active">Demo</span>
            </div>
            <div style={{ border: "1px solid #f36f21", borderRadius: 12, padding: 14, background: "#fff8f3" }}>
              <strong style={{ display: "block", marginBottom: 4 }}>Guardrisk Insurance Brokers</strong>
              <span style={{ fontSize: 13, color: "#667085" }}>Orange / white A4 business correspondence template</span>
            </div>
          </section>

          <section className="card pad">
            <div className="card-header" style={{ padding: 0, paddingBottom: 14, marginBottom: 16 }}><h2>Document details</h2></div>
            <div className="form-grid">
              <Field label="Date"><input className="input" value={document.document_date} onChange={(e) => update("document_date", e.target.value)} /></Field>
              <Field label="Reference"><input className="input" value={document.reference} onChange={(e) => update("reference", e.target.value)} /></Field>
              <Field label="Recipient"><input className="input" value={document.recipient_name} onChange={(e) => update("recipient_name", e.target.value)} /></Field>
              <Field label="Organisation"><input className="input" value={document.recipient_company} onChange={(e) => update("recipient_company", e.target.value)} /></Field>
              <Field label="Address" wide><textarea className="textarea" style={{ minHeight: 76 }} value={document.recipient_address} onChange={(e) => update("recipient_address", e.target.value)} /></Field>
              <Field label="Subject" wide><input className="input" value={document.subject} onChange={(e) => update("subject", e.target.value)} /></Field>
              <Field label="Letter body" wide><textarea className="textarea" style={{ minHeight: 250 }} value={document.body} onChange={(e) => update("body", e.target.value)} /></Field>
              <Field label="Signatory"><input className="input" value={document.signatory_name} onChange={(e) => update("signatory_name", e.target.value)} /></Field>
              <Field label="Title / organisation"><input className="input" value={document.signatory_title} onChange={(e) => update("signatory_title", e.target.value)} /></Field>
              <Field label="PDF signing" wide>
                <label style={{ display: "flex", gap: 10, alignItems: "center", fontWeight: 500, cursor: "pointer" }}>
                  <input type="checkbox" checked={document.include_signature_field} onChange={(e) => update("include_signature_field", e.target.checked)} />
                  Include a digital signature field in the exported PDF
                </label>
              </Field>
            </div>
          </section>

          <section className="card pad">
            <h2 style={{ marginTop: 0 }}>PDF output</h2>
            <div style={{ display: "grid", gap: 9, color: "#475467", fontSize: 13 }}>
              <div>✓ A4 Guardrisk letterhead</div>
              <div>✓ Multi-page body support</div>
              <div>✓ Controlled footer and contact details</div>
              <div>✓ Audit event when a PDF is generated</div>
              <div>✓ Real AcroForm digital signature field</div>
            </div>
          </section>
        </div>

        <section className="card" style={{ padding: 18, background: "#eef0f3", position: "sticky", top: 76 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
            <div>
              <strong>Live A4 preview</strong>
              <div style={{ fontSize: 12, color: "#667085", marginTop: 2 }}>The downloaded PDF uses the same structure.</div>
            </div>
            <span className="badge">PDF</span>
          </div>

          <div style={{ maxWidth: 760, margin: "0 auto", background: "white", boxShadow: "0 12px 34px rgba(16,24,40,.14)", minHeight: 970, position: "relative", overflow: "hidden" }}>
            <div style={{ height: 104, background: "#f36f21", color: "white", padding: "25px 42px", display: "flex", justifyContent: "space-between", gap: 24 }}>
              <div>
                <div style={{ fontSize: 29, fontWeight: 800, letterSpacing: "-.5px" }}>Guardrisk</div>
                <div style={{ fontSize: 11, fontWeight: 700, marginTop: 2 }}>INSURANCE BROKERS</div>
              </div>
              <div style={{ textAlign: "right", fontSize: 10, lineHeight: 1.55 }}>
                <strong>gRisk Document Studio</strong><br />
                Insurance | Medical Aid | Risk Management<br />
                Maseru, Lesotho
              </div>
            </div>
            <div style={{ height: 24, background: "#f5f5f5", padding: "6px 42px", fontSize: 8.5, color: "#667085", display: "flex", justifyContent: "space-between" }}>
              <span>LNDC Centre, Ground Floor, Kingsway Road, Maseru 100</span>
              <span>+266 2232 2537 | info@guardrisk.co.ls</span>
            </div>

            <div style={{ padding: "42px 58px 118px", color: "#252525", fontFamily: "Arial, sans-serif", fontSize: 13.2, lineHeight: 1.55 }}>
              <div style={{ textAlign: "right", marginBottom: 22 }}>
                <div>{document.document_date}</div>
                <strong style={{ fontSize: 12 }}>Ref: {document.reference}</strong>
              </div>

              <div style={{ whiteSpace: "pre-line", lineHeight: 1.48, marginBottom: 28 }}>
                {document.recipient_name}<br />
                {document.recipient_company}<br />
                {document.recipient_address}
              </div>

              <div style={{ color: "#f36f21", fontWeight: 800, marginBottom: 21, letterSpacing: ".2px" }}>{document.subject.toUpperCase()}</div>

              <div style={{ whiteSpace: "pre-wrap", minHeight: 310 }}>{document.body}</div>

              <div style={{ marginTop: 28 }}>Yours faithfully,</div>
              {document.include_signature_field ? (
                <div style={{ width: 300, height: 78, border: "1px dashed #a9a9a9", marginTop: 14, marginBottom: 17, display: "flex", alignItems: "flex-end", padding: 10, color: "#667085", fontSize: 10, background: "#fcfcfc" }}>
                  Digital signature field - click here to sign
                </div>
              ) : (
                <div style={{ width: 260, borderTop: "1px solid #333", marginTop: 55, marginBottom: 17 }} />
              )}
              <div style={{ fontWeight: 700 }}>{document.signatory_name}</div>
              <div style={{ fontSize: 12, color: "#475467" }}>{document.signatory_title}</div>
            </div>

            <div style={{ position: "absolute", left: 58, right: 58, bottom: 30, borderTop: "2px solid #f36f21", paddingTop: 9, display: "flex", justifyContent: "space-between", fontSize: 9, color: "#667085" }}>
              <span>Guardrisk Insurance Brokers | IBR No. 69915</span>
              <span>Page 1</span>
            </div>
          </div>
        </section>
      </div>

      <style jsx global>{`
        @media (max-width: 1180px) {
          .studio-grid { grid-template-columns: 1fr !important; }
          .studio-grid > section { position: static !important; }
        }
      `}</style>
    </AppShell>
  );
}
