"use client";

import { useState } from "react";
import AppShell from "@/components/AppShell";
import { apiDownloadPost } from "@/lib/api";
import { currentUser } from "@/lib/auth";

interface StudioDocument {
  document_title: string;
  recipient_name: string;
  recipient_company: string;
  recipient_address: string;
  recipient_phone: string;
  recipient_email: string;
  reference: string;
  document_date: string;
  subject: string;
  body: string;
  signatory_name: string;
  signatory_title: string;
  signatory_contact: string;
  include_signature_field: boolean;
  include_document_stamp: boolean;
}

const demoDocument: StudioDocument = {
  document_title: "FORMAL CORRESPONDENCE",
  recipient_name: "The Managing Director",
  recipient_company: "Demo Client (Pty) Ltd",
  recipient_address: "Maseru 100\nLesotho",
  recipient_phone: "+266 2231 0000",
  recipient_email: "director@democlient.co.ls",
  reference: "GRISK/DEMO/001",
  document_date: "08 September 2026",
  subject: "Demonstration of the gRisk Document Studio",
  body:
    "Dear Sir/Madam,\n\n" +
    "This demonstration letter was generated by the gRisk Document Studio using the Guardrisk orange and white letterhead. The design is intentionally clean, formal and suitable for client-facing correspondence.\n\n" +
    "The exported PDF includes a real digital-signature field. In a compatible PDF application, an authorised signatory can click the signature area and apply a certificate-based signature without rebuilding the document.\n\n" +
    "The same studio can be used for quotations, policy correspondence, claims, medical aid, finance, bonds, risk management and general operational letters.",
  signatory_name: "Authorised Signatory",
  signatory_title: "Guardrisk Insurance Brokers",
  signatory_contact: "+266 2232 2537 | info@guardrisk.co.ls",
  include_signature_field: true,
  include_document_stamp: true,
};

function Field({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) {
  return (
    <div className={wide ? "field full" : "field"}>
      <label>{label}</label>
      {children}
    </div>
  );
}

export default function DocumentStudioPage() {
  const user = currentUser();
  const canGenerate = Boolean(
    user?.isSuperuser ||
      user?.roles.some((role) => ["admin", "broker", "claims", "medical", "finance", "risk"].includes(role)),
  );
  const [document, setDocument] = useState<StudioDocument>({ ...demoDocument });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");

  function update<K extends keyof StudioDocument>(key: K, value: StudioDocument[K]) {
    setDocument((current) => ({ ...current, [key]: value }));
  }

  async function exportPdf() {
    setBusy(true);
    setError("");
    setNotice("");
    try {
      const result = await apiDownloadPost("/api/v1/document-studio/render", document);
      const url = URL.createObjectURL(result.blob);
      const anchor = window.document.createElement("a");
      anchor.href = url;
      anchor.download = result.filename || "guardrisk-document.pdf";
      anchor.click();
      URL.revokeObjectURL(url);
      setNotice("PDF generated with the Guardrisk orange letterhead and a real digital-signature field.");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unable to generate the PDF.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <AppShell>
      <div className="page-head">
        <div>
          <h1>Document Studio</h1>
          <p>Create formal Guardrisk correspondence with a live A4 preview and signing-ready PDF output.</p>
        </div>
        <div className="page-actions">
          <button className="button secondary" onClick={() => setDocument({ ...demoDocument })} disabled={busy}>
            Reset demo
          </button>
          <button className="button" onClick={() => void exportPdf()} disabled={busy || !canGenerate}>
            {busy ? "Generating PDF…" : "Export signing-ready PDF"}
          </button>
        </div>
      </div>

      {error && <div className="notice error" style={{ marginBottom: 14 }}>{error}</div>}
      {notice && <div className="notice" style={{ marginBottom: 14 }}>{notice}</div>}
      {!canGenerate && (
        <div className="notice" style={{ marginBottom: 14 }}>
          Your current role can preview the studio but cannot generate operational documents.
        </div>
      )}

      <div className="studio-grid-orange">
        <div className="studio-controls-orange">
          <section className="card pad studio-template-orange">
            <div className="studio-template-top-orange">
              <div className="studio-template-mark-orange">G</div>
              <div>
                <div className="studio-eyebrow-orange">ACTIVE TEMPLATE</div>
                <h2>Guardrisk Letterhead</h2>
                <p>Bright orange and white identity with the simple Guardrisk G, clean document hierarchy and digital signing.</p>
              </div>
            </div>
            <div className="studio-feature-row-orange">
              <span>A4 PDF</span>
              <span>Guardrisk orange</span>
              <span>Digital signature</span>
              <span>Audit logged</span>
            </div>
          </section>

          <section className="card pad">
            <div className="card-header studio-card-head-orange">
              <div><h2>Document identity</h2><p>Controls the title, date and reference.</p></div>
            </div>
            <div className="form-grid">
              <Field label="Document title" wide>
                <input className="input" value={document.document_title} onChange={(e) => update("document_title", e.target.value)} />
              </Field>
              <Field label="Date">
                <input className="input" value={document.document_date} onChange={(e) => update("document_date", e.target.value)} />
              </Field>
              <Field label="Reference">
                <input className="input" value={document.reference} onChange={(e) => update("reference", e.target.value)} />
              </Field>
            </div>
          </section>

          <section className="card pad">
            <div className="card-header studio-card-head-orange">
              <div><h2>Recipient</h2><p>Shown in the light information panel on the PDF.</p></div>
            </div>
            <div className="form-grid">
              <Field label="Recipient">
                <input className="input" value={document.recipient_name} onChange={(e) => update("recipient_name", e.target.value)} />
              </Field>
              <Field label="Organisation">
                <input className="input" value={document.recipient_company} onChange={(e) => update("recipient_company", e.target.value)} />
              </Field>
              <Field label="Address" wide>
                <textarea className="textarea" style={{ minHeight: 76 }} value={document.recipient_address} onChange={(e) => update("recipient_address", e.target.value)} />
              </Field>
              <Field label="Telephone">
                <input className="input" value={document.recipient_phone} onChange={(e) => update("recipient_phone", e.target.value)} />
              </Field>
              <Field label="Email">
                <input className="input" value={document.recipient_email} onChange={(e) => update("recipient_email", e.target.value)} />
              </Field>
            </div>
          </section>

          <section className="card pad">
            <div className="card-header studio-card-head-orange">
              <div><h2>Letter content</h2><p>The PDF wraps long content and continues onto additional pages automatically.</p></div>
            </div>
            <div className="form-grid">
              <Field label="Subject" wide>
                <input className="input" value={document.subject} onChange={(e) => update("subject", e.target.value)} />
              </Field>
              <Field label="Letter body" wide>
                <textarea className="textarea" style={{ minHeight: 285 }} value={document.body} onChange={(e) => update("body", e.target.value)} />
              </Field>
            </div>
          </section>

          <section className="card pad">
            <div className="card-header studio-card-head-orange">
              <div><h2>Signatory</h2><p>Configure the authorised signatory and signing options.</p></div>
            </div>
            <div className="form-grid">
              <Field label="Name">
                <input className="input" value={document.signatory_name} onChange={(e) => update("signatory_name", e.target.value)} />
              </Field>
              <Field label="Title / organisation">
                <input className="input" value={document.signatory_title} onChange={(e) => update("signatory_title", e.target.value)} />
              </Field>
              <Field label="Contact" wide>
                <input className="input" value={document.signatory_contact} onChange={(e) => update("signatory_contact", e.target.value)} />
              </Field>
              <Field label="Signing options" wide>
                <div className="studio-options-orange">
                  <label>
                    <input type="checkbox" checked={document.include_signature_field} onChange={(e) => update("include_signature_field", e.target.checked)} />
                    <span><strong>Digital signature field</strong><small>Creates a real PDF /Sig field for certificate signing.</small></span>
                  </label>
                  <label>
                    <input type="checkbox" checked={document.include_document_stamp} onChange={(e) => update("include_document_stamp", e.target.checked)} />
                    <span><strong>Signing-ready stamp</strong><small>Adds a neutral document-control stamp, not a fake signed seal.</small></span>
                  </label>
                </div>
              </Field>
            </div>
          </section>
        </div>

        <section className="card studio-preview-card-orange">
          <div className="studio-preview-head-orange">
            <div>
              <strong>Live A4 preview</strong>
              <span>Guardrisk orange letterhead · PDF output mirrors this layout</span>
            </div>
            <span className="badge active">Signing ready</span>
          </div>

          <div className="studio-paper-wrap-orange">
            <article className="studio-paper-orange">
              <div className="studio-top-swoop-orange" />
              <header className="studio-letterhead-orange">
                <div className="studio-logo-mark-orange">G</div>
                <div className="studio-brand-orange">GUARDRISK</div>
                <div className="studio-brand-sub-orange">DOCUMENT STUDIO</div>
                <div className="studio-services-orange">Insurance&nbsp;&nbsp; | &nbsp;&nbsp;Medical Aid&nbsp;&nbsp; | &nbsp;&nbsp;Bonds&nbsp;&nbsp; | &nbsp;&nbsp;Risk Management</div>
                <div className="studio-rule-orange" />
                <div className="studio-document-title-orange">{document.document_title.toUpperCase()}</div>
              </header>

              <div className="studio-recipient-card-orange">
                <div className="studio-recipient-accent-orange" />
                <div className="studio-recipient-content-orange">
                  <div className="studio-meta-row-orange">
                    <div><strong>Date:</strong><span>{document.document_date}</span></div>
                    <div><strong>Reference:</strong><span>{document.reference}</span></div>
                  </div>
                  <div className="studio-to-row-orange"><strong>To:</strong><span>{document.recipient_name}</span></div>
                  <div className="studio-recipient-company-orange">{document.recipient_company}</div>
                  <div className="studio-address-orange">{document.recipient_address}</div>
                  {(document.recipient_phone || document.recipient_email) && (
                    <div className="studio-recipient-contact-orange">
                      {document.recipient_phone && <span>Tel: {document.recipient_phone}</span>}
                      {document.recipient_phone && document.recipient_email && <i>•</i>}
                      {document.recipient_email && <span>Email: {document.recipient_email}</span>}
                    </div>
                  )}
                </div>
              </div>

              <div className="studio-letter-body-orange">
                <div className="studio-subject-orange">RE: {document.subject.toUpperCase()}</div>
                <div className="studio-body-copy-orange">{document.body}</div>
                <div className="studio-closing-orange">Yours faithfully,</div>

                <div className="studio-signature-panel-orange">
                  <div className="studio-signatory-copy-orange">
                    <strong>{document.signatory_name}</strong>
                    <b>{document.signatory_title}</b>
                    <span>{document.signatory_contact}</span>
                    <div className="studio-sign-row-orange">
                      <div>
                        <label>AUTHORISED SIGNATURE</label>
                        {document.include_signature_field ? (
                          <div className="studio-signature-field-orange">Click here to apply a certificate-based digital signature</div>
                        ) : (
                          <div className="studio-signature-line-orange" />
                        )}
                      </div>
                      <div className="studio-date-field-orange">
                        <label>DATE SIGNED</label>
                        <div />
                      </div>
                    </div>
                  </div>

                  {document.include_document_stamp && (
                    <div className="studio-stamp-orange">
                      <strong>G</strong>
                      <b>DOCUMENT STUDIO</b>
                      <span>SIGNING READY</span>
                      <small>gRisk</small>
                    </div>
                  )}
                </div>
              </div>

              <footer className="studio-letter-footer-orange">
                <div />
                <span>Guardrisk Insurance Brokers | LNDC Centre, Kingsway Road, Maseru 100 | +266 2232 2537 | info@guardrisk.co.ls</span>
                <small>Page 1</small>
              </footer>
              <div className="studio-bottom-swoop-orange" />
            </article>
          </div>
        </section>
      </div>

      <style jsx global>{`
        .studio-grid-orange {
          display: grid;
          grid-template-columns: minmax(330px, .8fr) minmax(570px, 1.2fr);
          gap: 18px;
          align-items: start;
        }
        .studio-controls-orange { display: grid; gap: 18px; }
        .studio-template-orange {
          background: linear-gradient(145deg, #fff 0%, #fff 68%, #fff5ef 100%);
          border: 1px solid #eee3dd;
        }
        .studio-template-top-orange { display: flex; gap: 15px; align-items: flex-start; }
        .studio-template-mark-orange {
          width: 54px; height: 54px; border-radius: 50%; background: #f35a1f; color: #fff;
          display: grid; place-items: center; font-size: 28px; font-weight: 800; flex: 0 0 auto;
          box-shadow: 0 5px 15px rgba(243,90,31,.2);
        }
        .studio-eyebrow-orange { font-size: 10px; letter-spacing: .13em; color: #f35a1f; font-weight: 800; margin-bottom: 4px; }
        .studio-template-orange h2 { margin: 0; color: #242424; }
        .studio-template-orange p { margin: 5px 0 0; color: #667085; line-height: 1.5; }
        .studio-feature-row-orange { display: flex; flex-wrap: wrap; gap: 7px; margin-top: 16px; }
        .studio-feature-row-orange span { padding: 6px 9px; border-radius: 999px; background: white; border: 1px solid #eee3dd; color: #475467; font-size: 11px; }
        .studio-card-head-orange { padding: 0 0 13px !important; margin-bottom: 16px !important; }
        .studio-card-head-orange p { margin: 4px 0 0; color: #667085; font-size: 12px; }
        .studio-options-orange { display: grid; gap: 10px; }
        .studio-options-orange > label { display: flex; gap: 10px; align-items: flex-start; cursor: pointer; padding: 10px 11px; border: 1px solid #ece7e4; border-radius: 10px; background: #fffdfc; }
        .studio-options-orange input { margin-top: 3px; accent-color: #f35a1f; }
        .studio-options-orange span { display: grid; gap: 2px; }
        .studio-options-orange strong { font-size: 12px; color: #344054; }
        .studio-options-orange small { color: #667085; line-height: 1.4; }

        .studio-preview-card-orange { padding: 18px; background: #eceff2; position: sticky; top: 76px; }
        .studio-preview-head-orange { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 13px; }
        .studio-preview-head-orange > div { display: grid; gap: 2px; }
        .studio-preview-head-orange span:not(.badge) { color: #667085; font-size: 12px; }
        .studio-paper-wrap-orange { max-width: 780px; margin: 0 auto; }
        .studio-paper-orange {
          aspect-ratio: 210 / 297; min-height: 980px; background: #fff; color: #242424;
          position: relative; box-shadow: 0 16px 42px rgba(16,24,40,.16); overflow: hidden;
          font-family: Arial, sans-serif;
        }
        .studio-top-swoop-orange {
          position: absolute; left: -75px; top: -88px; width: 330px; height: 165px; background: #f35a1f;
          border-radius: 0 0 100% 0; transform: rotate(-4deg); opacity: .98;
        }
        .studio-letterhead-orange { position: relative; z-index: 2; padding: 24px 54px 0; text-align: center; }
        .studio-logo-mark-orange {
          width: 50px; height: 50px; background: #f35a1f; color: white; border-radius: 50%; margin: 0 auto 10px;
          display: grid; place-items: center; font-size: 28px; font-weight: 800; box-shadow: 0 4px 12px rgba(243,90,31,.18);
        }
        .studio-brand-orange { color: #f35a1f; font-weight: 800; font-size: 25px; letter-spacing: .035em; }
        .studio-brand-sub-orange { color: #242424; font-weight: 800; font-size: 10px; letter-spacing: .17em; margin-top: 2px; }
        .studio-services-orange { color: #6b7280; font-size: 8.5px; margin-top: 7px; }
        .studio-rule-orange { height: 1px; background: #f35a1f; margin: 14px 0 11px; }
        .studio-document-title-orange { color: #242424; font-weight: 800; font-size: 14px; letter-spacing: .025em; }

        .studio-recipient-card-orange {
          margin: 18px 44px 0; min-height: 128px; background: #f7f7f7; border: 1px solid #dedede;
          border-radius: 10px; display: flex; overflow: hidden;
        }
        .studio-recipient-accent-orange { width: 8px; background: #f35a1f; flex: 0 0 auto; }
        .studio-recipient-content-orange { padding: 17px 20px 14px; width: 100%; font-size: 10.5px; }
        .studio-meta-row-orange { display: flex; justify-content: space-between; gap: 20px; margin-bottom: 9px; }
        .studio-meta-row-orange > div { display: flex; gap: 8px; }
        .studio-meta-row-orange strong, .studio-to-row-orange strong { color: #242424; }
        .studio-meta-row-orange span { color: #475467; }
        .studio-to-row-orange { display: flex; gap: 8px; margin-bottom: 3px; }
        .studio-to-row-orange span { font-weight: 700; color: #242424; }
        .studio-recipient-company-orange { margin-left: 22px; color: #344054; }
        .studio-address-orange { margin-left: 22px; white-space: pre-line; color: #475467; line-height: 1.4; }
        .studio-recipient-contact-orange { display: flex; justify-content: flex-end; align-items: center; gap: 7px; margin-top: 6px; color: #6b7280; font-size: 9px; }
        .studio-recipient-contact-orange i { font-style: normal; color: #f35a1f; }

        .studio-letter-body-orange { padding: 25px 44px 132px; font-size: 11.2px; line-height: 1.55; }
        .studio-subject-orange { color: #f35a1f; font-weight: 800; font-size: 11.2px; margin-bottom: 14px; border-bottom: 1px solid #f35a1f; padding-bottom: 6px; }
        .studio-body-copy-orange { white-space: pre-wrap; min-height: 278px; }
        .studio-closing-orange { margin: 19px 0 12px; }
        .studio-signature-panel-orange {
          min-height: 156px; background: #fff; border: 1px solid #f35a1f; border-radius: 10px;
          display: grid; grid-template-columns: 1fr 142px; gap: 18px; padding: 20px 20px 17px; align-items: center;
        }
        .studio-signatory-copy-orange { display: grid; align-content: start; }
        .studio-signatory-copy-orange > strong { color: #242424; font-size: 12px; margin-bottom: 4px; }
        .studio-signatory-copy-orange > b { color: #344054; font-size: 9.5px; margin-bottom: 4px; }
        .studio-signatory-copy-orange > span { color: #6b7280; font-size: 9px; }
        .studio-sign-row-orange { display: grid; grid-template-columns: minmax(0, 1fr) 116px; gap: 16px; margin-top: 18px; }
        .studio-sign-row-orange label { display: block; color: #f35a1f; font-size: 7px; letter-spacing: .05em; font-weight: 800; margin-bottom: 5px; }
        .studio-signature-field-orange { height: 37px; border: 1px solid #f35a1f; border-radius: 7px; background: white; color: #6b7280; font-size: 7.5px; padding: 10px 8px; line-height: 1.3; }
        .studio-signature-line-orange { height: 35px; border-bottom: 1px solid #444; }
        .studio-date-field-orange > div { height: 35px; border-bottom: 1px solid #777; }
        .studio-stamp-orange {
          width: 112px; height: 112px; border: 2px solid #f35a1f; border-radius: 50%;
          box-shadow: inset 0 0 0 4px white, inset 0 0 0 5px #ffb08a;
          margin: 0 auto; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center;
        }
        .studio-stamp-orange > strong { color: #f35a1f; font-size: 26px; line-height: 1; margin-bottom: 4px; }
        .studio-stamp-orange > b { color: #242424; font-size: 7px; }
        .studio-stamp-orange > span { color: #6b7280; font-size: 7px; font-weight: 800; margin-top: 4px; }
        .studio-stamp-orange > small { color: #8a8a8a; margin-top: 4px; }

        .studio-letter-footer-orange { position: absolute; left: 44px; right: 44px; bottom: 25px; color: #6b7280; font-size: 7.5px; text-align: center; z-index: 2; }
        .studio-letter-footer-orange > div { height: 1px; background: #e9e9e9; margin-bottom: 8px; }
        .studio-letter-footer-orange small { position: absolute; right: 0; top: 12px; }
        .studio-bottom-swoop-orange {
          position: absolute; left: -40px; right: -40px; bottom: -66px; height: 100px; background: #f35a1f;
          border-radius: 55% 45% 0 0 / 35% 35% 0 0; transform: rotate(-1deg); opacity: .98;
        }

        @media (max-width: 1180px) {
          .studio-grid-orange { grid-template-columns: 1fr; }
          .studio-preview-card-orange { position: static; }
        }
        @media (max-width: 720px) {
          .studio-paper-orange { min-height: 760px; }
          .studio-letterhead-orange { padding-left: 30px; padding-right: 30px; }
          .studio-recipient-card-orange { margin-left: 24px; margin-right: 24px; }
          .studio-letter-body-orange { padding-left: 24px; padding-right: 24px; }
          .studio-signature-panel-orange { grid-template-columns: 1fr; }
          .studio-stamp-orange { display: none; }
          .studio-letter-footer-orange { left: 24px; right: 24px; }
        }
      `}</style>
    </AppShell>
  );
}
